# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/masterXDC/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/Main/Main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main || ORIG_REF_NAME==Main} -quiet] -quiet

# IP: bd/Main/ip/Main_processing_system7_0_0/Main_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_processing_system7_0_0 || ORIG_REF_NAME==Main_processing_system7_0_0} -quiet] -quiet

# IP: bd/Main/ip/Main_axi_quad_spi_0_0/Main_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_axi_quad_spi_0_0 || ORIG_REF_NAME==Main_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/Main/ip/Main_auto_pc_0/Main_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_auto_pc_0 || ORIG_REF_NAME==Main_auto_pc_0} -quiet] -quiet

# IP: bd/Main/ip/Main_ps7_0_axi_periph_0/Main_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_ps7_0_axi_periph_0 || ORIG_REF_NAME==Main_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Main/ip/Main_rst_ps7_0_100M_0/Main_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_rst_ps7_0_100M_0 || ORIG_REF_NAME==Main_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Main/ip/Main_system_ila_0_0/Main_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_system_ila_0_0 || ORIG_REF_NAME==Main_system_ila_0_0} -quiet] -quiet

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/Main_ooc.xdc
