# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.srcs/sources_1/bd/Main/ip/Main_auto_pc_0/Main_auto_pc_0.xci
# IP: The module: 'Main_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_auto_pc_0/Main_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.srcs/sources_1/bd/Main/ip/Main_auto_pc_0/Main_auto_pc_0.xci
# IP: The module: 'Main_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_auto_pc_0/Main_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
