# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.srcs/sources_1/bd/Main/ip/Main_system_ila_0_0/Main_system_ila_0_0.xci
# IP: The module: 'Main_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/bd_65d3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3 || ORIG_REF_NAME==bd_65d3} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_0/bd_65d3_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_ila_lib_0 || ORIG_REF_NAME==bd_65d3_ila_lib_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_1/bd_65d3_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_g_inst_0 || ORIG_REF_NAME==bd_65d3_g_inst_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_2/bd_65d3_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_slot_0_aw_0 || ORIG_REF_NAME==bd_65d3_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_3/bd_65d3_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_slot_0_w_0 || ORIG_REF_NAME==bd_65d3_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_4/bd_65d3_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_slot_0_b_0 || ORIG_REF_NAME==bd_65d3_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_5/bd_65d3_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_slot_0_ar_0 || ORIG_REF_NAME==bd_65d3_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_6/bd_65d3_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_slot_0_r_0 || ORIG_REF_NAME==bd_65d3_slot_0_r_0} -quiet] -quiet

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_65d3_ila_lib_0 || ORIG_REF_NAME==bd_65d3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_65d3_ila_lib_0 || ORIG_REF_NAME==bd_65d3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_0/bd_65d3_ila_lib_0_ooc.xdc

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/bd_65d3_ooc.xdc

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/Main_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.srcs/sources_1/bd/Main/ip/Main_system_ila_0_0/Main_system_ila_0_0.xci
# IP: The module: 'Main_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/bd_65d3.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3 || ORIG_REF_NAME==bd_65d3} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_0/bd_65d3_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_ila_lib_0 || ORIG_REF_NAME==bd_65d3_ila_lib_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_1/bd_65d3_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_g_inst_0 || ORIG_REF_NAME==bd_65d3_g_inst_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_2/bd_65d3_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_slot_0_aw_0 || ORIG_REF_NAME==bd_65d3_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_3/bd_65d3_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_slot_0_w_0 || ORIG_REF_NAME==bd_65d3_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_4/bd_65d3_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_slot_0_b_0 || ORIG_REF_NAME==bd_65d3_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_5/bd_65d3_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_slot_0_ar_0 || ORIG_REF_NAME==bd_65d3_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_6/bd_65d3_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_65d3_slot_0_r_0 || ORIG_REF_NAME==bd_65d3_slot_0_r_0} -quiet] -quiet

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_65d3_ila_lib_0 || ORIG_REF_NAME==bd_65d3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_65d3_ila_lib_0 || ORIG_REF_NAME==bd_65d3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/ip/ip_0/bd_65d3_ila_lib_0_ooc.xdc

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/bd_0/bd_65d3_ooc.xdc

# XDC: c:/Users/Irene/Desktop/FPGAWars/prueba1/FPGAWars.gen/sources_1/bd/Main/ip/Main_system_ila_0_0/Main_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
